"""create contracts table

Revision ID: b52a537a3f31
Revises:
Create Date: 2026-07-29 18:50:31.064019

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b52a537a3f31"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum("RENEW", "SUBSCRIBE", "BUY", "PAY", "CANCEL", name="action"),
            nullable=False,
        ),
        sa.Column("max_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="frequency"),
            nullable=False,
        ),
        sa.Column("approval_mode", sa.Enum("AUTO", "MANUAL", name="approvalmode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "REVOKED", name="contractstatus"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contracts")
    # ### end Alembic commands ###
